pipeline {
    agent none
    stages{
        stage('build'){
            agent{
                docker{
                    image 'python:3.11-slim'
                    args '--user root'
                    }
                    }

            steps{
                echo 'Compiling vote app.'
                dir('vote'){

                        sh "pip install -r requirements.txt"

                }
            }
        }
        stage('test'){

            agent {
                docker{
                    image 'python:3.11-slim'
                    args '--user root'
                    }
                    }
            steps{
                echo 'Running Unit Tests on vote app.'
                dir('vote'){

                        sh "pip install -r requirements.txt"
                        sh 'nosetests -v'


                }
            }
        }

        stage('docker image'){
          agent any
          steps{
            dir('vote'){
              echo 'packaging vote app as image'
              script{
                docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin'){
                  def workerImage=docker.build("simonzn/vote:v${env.BUILD_ID}", ".")
                  workerImage.push()
                  workerImage.push("latest")
                }
              }
            }
          }
        }

    }
    post {
        always{
            echo 'Pipeline for vote is complete'
        }
    }

}


