volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:

  vote:
    image: simonzn/vote:latest
    ports:
      - 5000:80
    networks:
      - instavote
    depends_on:
      - redis

  result:
    image: simonzn/result:latest
    ports:
      - 5001:80
    networks:
      - instavote
    depends_on:
      - db

  worker:
    image: simonzn/worker:latest
    networks:
      - instavote
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    networks:
      - instavote

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    networks:
      - instavote