pipeline {
    agent none
    stages{
        stage('build'){
            agent {
              docker {
                image 'maven:3.9.8-eclipse-temurin-21-alpine'
                args '-v $HOME/.m2:/root/.m2'
              }
            }
            when {
              changeset '**/worker/**'
            }
            steps{
                echo 'building worker app'
                dir('worker'){
                  sh 'mvn compile'
                }
            }
        }
        stage('test'){
            agent {
              docker {
                image 'maven:3.9.8-eclipse-temurin-21-alpine'
                args '-v $HOME/.m2:/root/.m2'
              }
            }
            when {
              changeset '**/worker/**'
            }
            steps{
                echo 'running unit tests on worker app'
                dir('worker'){
                  sh 'mvn clean test'
                }
            }
        }
        stage('package'){
            agent {
              docker {
                image 'maven:3.9.8-eclipse-temurin-21-alpine'
                args '-v $HOME/.m2:/root/.m2'
              }
            }
            when {
              changeset '**/worker/**'
              branch 'master'
            }
            steps{
                echo 'packaging worker app into a jarfile'
                dir('worker'){
                  sh 'mvn package -DskipTests'
                  archiveArtifacts artifacts: '**/target/*.jar', fingerprint:  true
                }
            }
        }
        stage('docker image'){
          when{
            branch 'master'
          }
          agent any
          steps{
            dir('worker'){
              echo 'packaging worker app as image'
              script{
                docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin'){
                  defworkerImage=docker.build("simonzn/worker:v${env.BUILD_ID}", ".")
                  workerImage.push()
                  workerImage.push("latest")
                }
              }
            }
          }
        }
    }
    post{
        always{
            echo 'the job is complete'

    }
  }
}
