pipeline {
    agent none
    stages{
        stage('docker image'){
          agent any
          steps{
            dir('worker'){
              echo 'packaging worker app as image'
              script{
                docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin'){
                  def workerImage=docker.build("simonzn/worker:v${env.BUILD_ID}", ".")
                  workerImage.push()
                  workerImage.push("latest")
                }
              }
            }
          }
        }
    }
    post{
        always{
            echo 'the job is complete'

    }
  }
}
